Enable defining a unique GUID in case the LDAP server does not implement RFC4530 entryUUID.
This commit also traps directorytree/ldaprecord-laravel's getAuthIdentifier() which will throw a TypeError if the User::guidKey doesnt exist. Should help #433